# Generated by Django 5.2.8 on 2025-12-07 14:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='direccion',
            options={'ordering': ['-principal', '-created_at']},
        ),
        migrations.AddField(
            model_name='direccion',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='direccion',
            name='numero',
            field=models.CharField(blank=True, max_length=30, verbose_name='Número'),
        ),
        migrations.AddField(
            model_name='direccion',
            name='principal',
            field=models.BooleanField(default=False, verbose_name='Dirección principal'),
        ),
        migrations.AlterField(
            model_name='direccion',
            name='calle',
            field=models.CharField(max_length=200, verbose_name='Calle / Dirección'),
        ),
        migrations.AlterField(
            model_name='direccion',
            name='comuna',
            field=models.CharField(max_length=100, verbose_name='Comuna'),
        ),
        migrations.AlterField(
            model_name='direccion',
            name='referencia',
            field=models.CharField(blank=True, max_length=250, verbose_name='Referencia'),
        ),
        migrations.AlterField(
            model_name='direccion',
            name='telefono',
            field=models.CharField(blank=True, max_length=30, verbose_name='Teléfono'),
        ),
    ]
