# Generated by Django 5.2.8 on 2025-12-09 01:28

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_alter_direccion_options_direccion_created_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='direccion',
            options={},
        ),
        migrations.RemoveField(
            model_name='direccion',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='direccion',
            name='telefono',
        ),
        migrations.AddField(
            model_name='direccion',
            name='ciudad',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='direccion',
            name='nombre',
            field=models.CharField(default='Direccion', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='direccion',
            name='calle',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='direccion',
            name='comuna',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='direccion',
            name='numero',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='direccion',
            name='principal',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='direccion',
            name='referencia',
            field=models.TextField(blank=True, null=True),
        ),
    ]
