# Generated by Django 5.2.8 on 2025-11-17 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_categoria_producto_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clienteprofile',
            name='rut',
            field=models.CharField(blank=True, max_length=12, null=True, unique=True),
        ),
    ]
