# Generated by Django 5.2.8 on 2025-12-07 14:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0002_pedido_direccion'),
        ('usuarios', '0002_alter_direccion_options_direccion_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='direccion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos', to='usuarios.direccion'),
        ),
    ]
